USER_ROLE_SUPER_USER = 1
USER_ROLE_GUEST = 2
USER_ROLES = (
    (USER_ROLE_SUPER_USER, 'super admin'),
    (USER_ROLE_GUEST, 'guest')
)

USER_SEX_MALE = 1
USER_SEX_FEMALE = 2
USER_SEX = (
    (USER_SEX_MALE, 'male'),
    (USER_SEX_FEMALE, 'female')
)

JOURNAL_TYPE_BULLET = 1
JOURNAL_TYPE_FOOD = 2
JOURNAL_TYPE_TRAVEL = 3
JOURNAL_TYPE_SPORT = 4
JOURNAL_TYPE = (
    (JOURNAL_TYPE_BULLET, 'Bullet'),
    (JOURNAL_TYPE_FOOD, 'Food'),
    (JOURNAL_TYPE_SPORT, 'Sport'),
    (JOURNAL_TYPE_TRAVEL, 'Travel')
)